import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { island as generatedIsland } from '../../shared/island';
import { Bubbles } from './bubbles';
import { Cartly } from './cartly';
import { loadManifest } from './chars';
import { buildDistance } from './distance';
import { Entities } from './entities';
import { CityFeed } from './feed';
import { Atmosphere } from './fx';
import { HubLink } from './hublink';
import { IrsEncounter } from './irs';
import { Minimap } from './minimap';
import { Multiplayer } from './mp';
import { Player } from './player';
import { initProps3d } from './props3d';
import { StartScreen } from './start';
import { TouchControls } from './touch';
import { Ui } from './ui';
import { npcLabel, roleTitle } from './util';
import { WaterFx } from './water-fx';
import { buildIsland, IslandView } from './world';

/**
 * Composition root, and nothing else: construct the modules, hand them their
 * collaborators, run the frame loop. Feature logic lives with the feature —
 * the IRS encounter in irs/, ride-hailing in cartly/, every ServerFrame in
 * hublink.ts. If an edit here is more than wiring, it belongs in a module.
 */

const COARSE = matchMedia('(pointer: coarse)').matches;
const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setPixelRatio(Math.min(devicePixelRatio, COARSE ? 1.75 : 2)); // phone GPUs breathe easier
renderer.setSize(innerWidth, innerHeight);
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.05;
document.body.append(renderer.domElement);

const scene = new THREE.Scene();
const fx = new Atmosphere(scene);
const player = new Player(renderer.domElement);
const entities = new Entities();
scene.add(entities.group, player.view.root);
const bubbles = new Bubbles();
const ui = new Ui();
const feed = new CityFeed();
const minimap = new Minimap();
new TouchControls(player); // joystick + compact chrome on coarse-pointer devices
// A lid, not a gate: everything above already renders behind it from the
// first frame, so the bar below reports asset streaming, not readiness.
const start = new StartScreen(COARSE);

// ── multiplayer (worldplay4's Playroom stack): the URL is the invite link ──
const mp = new Multiplayer(scene);
document.querySelector('#hud')!.insertAdjacentHTML(
  'beforeend', `<span class="chip link" id="c-invite">🔗 …</span>`);
const inviteChip = document.querySelector<HTMLElement>('#c-invite')!;
inviteChip.addEventListener('click', () => {
  navigator.clipboard?.writeText(location.href)
    .then(() => ui.toast('invite link copied — send it to a friend!', '🔗'))
    .catch(() => ui.toast(location.href, '🔗'));
});
mp.onStatus = (status, room) => {
  inviteChip.textContent = status === 'online' ? `🔗 ${room ?? 'room'} · invite` : '🔗 solo';
  if (status === 'online') ui.toast('multiplayer on — click 🔗 to copy the invite link', '🎮');
  start.paintQr(); // the room code is in the URL now, so the QR must be re-cut
};
let mpCount = 0;
mp.onRoster = (names) => {
  if (names.length > mpCount) ui.toast(`${names[names.length - 1]} joined the city!`, '👋');
  else if (names.length < mpCount) ui.toast('a traveller left the city', '👋');
  mpCount = names.length;
};
void mp.join();

const waterFx = new WaterFx();
scene.add(waterFx.group);

const composer = new EffectComposer(renderer);
composer.addPass(new RenderPass(scene, player.camera));
const bloom = new UnrealBloomPass(new THREE.Vector2(innerWidth, innerHeight), 0.28, 0.65, 0.88);
composer.addPass(bloom);
composer.addPass(new OutputPass());

// ── the city itself ─────────────────────────────────────────────────────────
// The island is deterministic and generated by the exact code the hub runs
// (shared/island.ts), so the client builds it immediately — the game works on
// a static host with no hub (Playroom heroes only, citizens asleep), and the
// hub, when reachable, animates NPCs/weather/quests on top.
let propsReady: Promise<void>;
const island: IslandView = new IslandView(generatedIsland);
{
  const built = buildIsland(generatedIsland);
  scene.add(built.group);
  fx.attachWorld(built);
  propsReady = initProps3d(scene, island, // Tripo kawaii props + the parked fleet
    (done, total) => start.setProgress(done / total));
  // The painted distance: rocks, headlands, a skyline — so the eye never
  // finds the edge of the tile grid.
  const far = buildDistance(new THREE.Vector3(generatedIsland.size / 2, 0, generatedIsland.size / 2));
  scene.add(far.group);
  fx.attachDistance(far.layers);
  minimap.bind(island);
}
const spawnPos = generatedIsland.pois.find((p) => p.id === 'plaza')?.pos ?? { x: 52, y: 2, z: 43 };
player.bindIsland(island, new THREE.Vector3(spawnPos.x + 1.4, spawnPos.y, spawnPos.z + 1.6));
const boardPos: THREE.Vector3 | null = (() => {
  const b = generatedIsland.pois.find((p) => p.id === 'board');
  return b ? new THREE.Vector3(b.pos.x, b.pos.y, b.pos.z) : null;
})();

// ── the sea ────────────────────────────────────────────────────────────────
player.onEnterWater = (x, z) => waterFx.splash(x, z, 1);
player.onLeaveWater = () => waterFx.splash(player.pos.x, player.pos.z, 0.5);
player.onCurrent = () => ui.toast('the current out here is brutal — best turn back', '🌊');

// ── features ────────────────────────────────────────────────────────────────
const toast = (text: string, icon: string) => ui.toast(text, icon);

const cartly = new Cartly(scene, player, () => island, {
  toast,
  resolveNpc: (id) => {
    const e = entities.npc(id);
    return e ? { label: e.data.name, x: e.view.root.position.x, z: e.view.root.position.z } : null;
  },
});

const irs = new IrsEncounter(scene, generatedIsland, player, toast);
irs.onSeclusion = (secluded) => { mp.avatarsVisible = !secluded; };
// Mark trash-talks in the same kawaii bubbles as every citizen.
irs.speak = (text) => bubbles.push('mark', 'Mark', '#ffd9c9', 'commit', text, 'neutral');

const hub = new HubLink({ player, entities, ui, fx, bubbles, feed, cartly, irs });

if (import.meta.env.DEV) { // console-inspection only — never shipped
  (window as unknown as Record<string, unknown>).__sfq = { island, player, mp, cartly, irs };
}

// ── interactions: ONE priority list serves both the E key and the pill ─────
interface Interactable { prompt(): string | null; act(): boolean }
const interactables: Interactable[] = [
  irs,
  cartly,
  { // talk to the nearest citizen
    prompt: () => {
      const npc = entities.nearestNpc(player.pos, 3.4);
      return npc ? `<kbd>E</kbd> talk to ${roleTitle(npc.role)} ${npc.name} 💬` : null;
    },
    act: () => {
      const npc = entities.nearestNpc(player.pos, 3.4);
      if (!npc) return false;
      ui.openTalk(npc.id, npcLabel(npc));
      hub.interact(npc.id); // the NPC stops and faces the player
      return true;
    },
  },
  { // the notice board
    prompt: () => (boardPos && boardPos.distanceTo(player.pos) < 3.2 ? `<kbd>E</kbd> read the notice board 📋` : null),
    act: () => {
      if (!boardPos || boardPos.distanceTo(player.pos) >= 3.2) return false;
      ui.openQuests();
      return true;
    },
  },
];

/** The E action — also fired by tapping the interaction pill on touch. */
function interact(): void {
  for (const i of interactables) if (i.act()) return;
}
ui.onPromptTap = interact;

function nearestPoiLabel(): string {
  let best = 'the village';
  let bestD = Infinity;
  for (const p of generatedIsland.pois) {
    const d = (p.pos.x - player.pos.x) ** 2 + (p.pos.z - player.pos.z) ** 2;
    if (d < bestD) { bestD = d; best = p.label; }
  }
  return best;
}

addEventListener('keydown', (e) => {
  if (e.code === 'Escape' && ui.questsOpen) ui.closeQuests();
  if (document.body.dataset.typing === '1') return;
  if (e.code === 'KeyP') { cartly.togglePhone(nearestPoiLabel()); return; }
  if (e.code === 'KeyL') { feed.toggle(); return; }
  if (e.code === 'KeyE') interact();
});

addEventListener('resize', () => {
  player.camera.aspect = innerWidth / innerHeight;
  player.camera.updateProjectionMatrix();
  renderer.setSize(innerWidth, innerHeight);
  composer.setSize(innerWidth, innerHeight);
});

// LOADING → START once the wardrobe and the props are in; the floor is there
// so a stalled CDN can never park the button on LOADING.
void Promise.all([loadManifest(), propsReady!]).then(() => start.ready());
setTimeout(() => start.ready(), 9000);

const playerAnchor = new THREE.Vector3();
const clock = new THREE.Clock();
let mmAcc = 0;
const sizeProbe = new THREE.Vector2();
renderer.setAnimationLoop(() => {
  // Some hosts (emulated viewports, panes) never fire `resize` — poll instead.
  const size = renderer.getSize(sizeProbe);
  if (size.x !== innerWidth || size.y !== innerHeight) {
    player.camera.aspect = innerWidth / innerHeight;
    player.camera.updateProjectionMatrix();
    renderer.setSize(innerWidth, innerHeight);
    composer.setSize(innerWidth, innerHeight);
  }
  const dt = Math.min(clock.getDelta(), 0.1);
  player.update(dt);
  cartly.update(dt); // after player.update so a ride overrides the hero's pose
  entities.update(dt);
  mp.update(dt);
  mp.setPose({ x: player.pos.x, y: player.pos.y, z: player.pos.z, rot: player.rot, anim: player.anim, t: Date.now() });
  if (player.swimming) waterFx.trail(player.pos.x, player.pos.z, player.anim !== 'idle', dt);
  waterFx.update(dt);
  fx.update(dt, player.camera);
  irs.update(dt);

  mmAcc += dt;
  if (!COARSE && mmAcc > 0.1) { // 10Hz redraw — a full-canvas repaint per frame is waste
    mmAcc = 0;
    minimap.update(
      { x: player.pos.x, z: player.pos.z, rot: player.rot },
      entities.npcList().map((n) => {
        const e = entities.npc(n.id)!;
        return { x: e.view.root.position.x, z: e.view.root.position.z, color: n.bubbleTint || '#ffd3b6' };
      }),
      cartly.cartPos ? { x: cartly.cartPos.x, z: cartly.cartPos.z, color: '#ffd977' } : null,
      mp.dots(),
    );
  }

  // Interaction prompt: the first interactable with something to say wins.
  if (document.body.dataset.typing !== '1') {
    let prompt: string | null = null;
    for (const i of interactables) { prompt = i.prompt(); if (prompt) break; }
    ui.setPrompt(prompt);
  } else ui.setPrompt(null);

  bubbles.update(dt, player.camera, (who) =>
    who === 'player'
      ? playerAnchor.copy(player.pos).add(new THREE.Vector3(0, 2.05, 0))
      : who === 'mark' ? irs.markAnchor()
      : entities.anchor(who));

  composer.render();
});
